# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  run:debug:
    deps: [build:debug]
    cmd: ./build/debug/model-viewer

  run:release:
    deps: [build:release]
    cmd: ./build/release/model-viewer

  build:debug:
    deps: [config_cmake]
    cmd: cmake --build --preset debug

  test:debug:
    deps: [build:debug]
    cmd: ctest --test-dir build/debug --output-on-failure

  build:release:
    deps: [config_cmake]
    cmd: cmake --build --preset release

  test:release:
    deps: [build:release]
    cmd: ctest --test-dir build/release --output-on-failure

  test:
    deps: [test:debug]

  config_cmake:
    sources:
      - ./**/CMakeLists.txt
      - CMakePresets.json
      - exclude: ./build/**/*
    cmds:
      - cmake --preset debug
      - cmake --preset release
